[package]
name = "passpartout_printer"
version = "0.1.0"
authors = ["ostrosco <ostrosco@fastmail.fm>"]

[dependencies]
enigo = "0.0.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
failure = "0.1.1"
